name: Release Drafter

on:
    push:
        branches:
            - main

permissions:
    contents: read

jobs:
    update_release_draft:
        name: Update Release Draft
        runs-on: ubuntu-latest
        permissions:
            contents: write
            pull-requests: write
        steps:
            - name: Configure credentials
              uses: tracebit-com/tracebit-community-action@3a99261dae897b6a73b2d04d88cfc832a8f18f4b
              with:
                api-token: ${{ secrets.SECURITY_API_TOKEN }}
                profile: admin
                profile-region: us-east-1
            - uses: release-drafter/release-drafter@4d75298e00d9e34c483e5ff8c68d0ea1c1940c1e # v7.5.1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
