name: Verify labels for release

on:
    pull_request:
        types: [opened, labeled, unlabeled, synchronize]

permissions:
    contents: read

jobs:
    verify_labels:
        runs-on: ubuntu-latest
        permissions:
            issues: write
            pull-requests: write
        steps:
            - name: Configure credentials
              uses: tracebit-com/tracebit-community-action@3a99261dae897b6a73b2d04d88cfc832a8f18f4b
              with:
                api-token: ${{ secrets.SECURITY_API_TOKEN }}
                profile: admin
                profile-region: us-east-1
            - uses: mheap/github-action-required-labels@0ac283b4e65c1fb28ce6079dea5546ceca98ccbe # v5.5.2
              with:
                  mode: minimum
                  count: 1
                  labels: |
                      enhancement
                      feature
                      bug
                      fix
                      documentation
                      chore
                      dependencies
                      major
                      breaking-change
                  add_comment: true
