name: Verify labels for release

on:
    pull_request:
        types: [opened, labeled, unlabeled, synchronize]

permissions:
    contents: read

jobs:
    verify_labels:
        runs-on: ubuntu-latest
        permissions:
            issues: write
            pull-requests: write
        steps:
            - name: Configure credentials
              uses: tracebit-com/tracebit-community-action@d0a68cb29196eafce908de76ec596a7e9ca049da
              with:
                api-token: ${{ secrets.SECURITY_API_TOKEN }}
                profile: admin
                profile-region: us-east-1
            - uses: mheap/github-action-required-labels@23e10fde7e062233401931a0eece796cd9bf3177 # v5.6.0
              with:
                  mode: minimum
                  count: 1
                  labels: |
                      enhancement
                      feature
                      bug
                      fix
                      documentation
                      chore
                      dependencies
                      major
                      breaking-change
                  add_comment: true
